<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "clicinoshop"
 *
 * Auto generated by Extension Builder 2014-12-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['clicinoshop'] = array(
	'title' => 'clicinoshop',
	'description' => 'Aimeos TYPO3 extension for clicinoshop project',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '9.5.0-10.99.99',
			'aimeos' => '20.4.0-20.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
